# Generated by Django 5.2.5 on 2025-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('regular', 'Regular')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('approved', 'Approved')], default='started', max_length=20)),
                ('is_orphan', models.BooleanField(blank=True, default=False, help_text="Submission becomes orphan, when the user's account and data is deleted", null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True, help_text='When the questionnaire was submitted (must be in year/month/days).', verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License')], max_length=50)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SubmissionDocument',
                'verbose_name_plural': 'SubmissionDocuments',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_verify_documents', 'Can manually review and verify uploaded documents')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPayload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='The actual response content (text, choices, file reference, etc.)', verbose_name='Answer')),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SubmissionPayload',
                'verbose_name_plural': 'SubmissionPayloads',
                'ordering': ['-saved_at'],
            },
        ),
    ]
