# Generated by Django 5.2.5 on 2025-09-29 12:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License')], max_length=50)),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SubmissionDocument',
                'verbose_name_plural': 'SubmissionDocuments',
                'ordering': ['-uploaded_at'],
                'permissions': [],
                'indexes': [models.Index(fields=['doc_type'], name='idx_by_document_type'), models.Index(fields=['uploaded_at'], name='idx_by_upload_time')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPayload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='The actual response content (text, choices, file reference, etc.)', verbose_name='Answer')),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SubmissionPayload',
                'verbose_name_plural': 'SubmissionPayloads',
                'ordering': ['-saved_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='payload_gin_idx')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_status', models.CharField(choices=[('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('questionnaire_type', models.CharField(choices=[('verification', 'Verification'), ('mandatory', 'Mandatory'), ('regular', 'Regular')], max_length=50)),
                ('questionnaire_scope', models.CharField(choices=[('public', 'Public'), ('assigned', 'Assigned')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now=True, help_text='When the questionnaire was submitted (must be in year/month/days).', verbose_name='Submitted At')),
                ('is_failed', models.BooleanField(blank=True, default=False, help_text='After X failed attempts to verify user identity', null=True)),
                ('is_orphan', models.BooleanField(blank=True, default=False, help_text="Submission becomes orphan, when the user's account and data is deleted", null=True)),
                ('patched_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.', verbose_name='Patched At')),
                ('questionnaire', models.ForeignKey(help_text='The questionnaire being filled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='questionnaire.questionnaire', verbose_name='Questionnaire')),
                ('staff_id', models.ForeignKey(blank=True, help_text='Approved or rejected by admin manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patched_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user that submitted the questionnaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('docs', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.submissiondocument')),
                ('payload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='submission.submissionpayload', verbose_name='Payload')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(condition=models.Q(('questionnaire_type', 'verification')), fields=['questionnaire_type'], name='idx_verification_submissions'), models.Index(fields=['submitted_at'], name='idx_submitted_at'), models.Index(fields=['submission_status'], name='idx_submission_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'questionnaire'), name='uq_user_questionnaire')],
            },
        ),
    ]
