# Generated by Django 5.2.5 on 2025-09-06 18:55

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0002_initial'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Approved by admin manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='questionnaire',
            field=models.ForeignKey(help_text='The questionnaire being filled.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='questionnaire.questionnaire', verbose_name='Questionnaire'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(help_text='The user that submitted the questionnaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='submissiondocument',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='submission.submission'),
        ),
        migrations.AddField(
            model_name='submissionpayload',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='submission.submission'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(condition=models.Q(('submission_type', 'mandatory')), fields=['submission_type'], name='idx_mandatory_submissions'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='idx_submitted_at'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='idx_status_started'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'questionnaire'), name='uq_user_questionnaire'),
        ),
        migrations.AddIndex(
            model_name='submissiondocument',
            index=models.Index(fields=['submission'], name='idx_by_submission'),
        ),
        migrations.AddIndex(
            model_name='submissiondocument',
            index=models.Index(fields=['document_type'], name='idx_by_document_type'),
        ),
        migrations.AddIndex(
            model_name='submissiondocument',
            index=models.Index(fields=['uploaded_at'], name='idx_by_upload_time'),
        ),
        migrations.AddIndex(
            model_name='submissionpayload',
            index=models.Index(fields=['submission'], name='index_by_submission'),
        ),
        migrations.AddIndex(
            model_name='submissionpayload',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='payload_gin_idx'),
        ),
    ]
