# Generated by Django 5.2.5 on 2025-09-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Users that this questionnaire is assigned to', related_name='assigned_questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='submitted_by',
            field=models.ManyToManyField(blank=True, help_text='Users the questionnaire was submitted by', related_name='submitted_questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questionnaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_items', to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='Questions included in this questionnaire', related_name='questionnaire', through='questionnaire.QuestionnaireQuestion', to='questionnaire.question'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['reference_code', 'question_type'], name='questionnai_referen_aee6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by', 'created_at'], name='questionnai_created_0a9e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnairequestion',
            index=models.Index(fields=['questionnaire', 'order_index'], name='qitem_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairequestion',
            unique_together={('questionnaire', 'order_index'), ('questionnaire', 'question')},
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['status', 'questionnaire_type'], name='questionnai_status_34bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['name', 'status'], name='questionnai_name_76f6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['created_by', 'status'], name='questionnai_created_9c7f69_idx'),
        ),
    ]
